### ISSUE TITLE
Muk theme fails after change colors.

### ISSUE THREAD

**Issue by borisduin** [muk-it/odoo-modules#7]
Same as https://github.com/muk-it/odoo-modules/issues/4.

Oddo version: Odoo 17 Comunity.
Error: ValueError: File(s) /muk_web_colors/static/src/scss/colors_light.scss not found in bundle web._assets_primary_variables.
Odoo service is unavailable after this error.
I stop odoo service, start odoo shell and  run self.env['ir.module.module'].search([('name', '=', 'muk_web_colors')]).button_immediate_uninstall() to remove module, start odoo service and odoo is operative again. I resintall module, and muk themes keep with defaults colors.
But, when i change some muk theme colors in setting page, odoo fails again.

**Comment by trungnguyen119** [comment]
Same here, even after remove the module folder or stop override web._assets_primary_variables in the manifest file it is still return 500 error, the only way is to uninstall the module, hope this get fix soon.

**Comment by Kaliuta** [comment]
He also repeated this mistake. Here are the steps:
1. Change the brand color.
2. Save.
3. Change the brand color again (second time).
4. Save.
5. Result: Error.

The error occurs if the website module is installed.
Everything works fine without the website module installed.

I understood that it is related to the method:

def _get_custom_attachment(self, custom_url, op='=')

which is located in the path: /addons/website/models/assets.py

If the override of this method is commented out, there will be no error.

This requires additional research, but I think the problem is that the attachment is filtered by website_id, and style attachments generated by this module may not have this field, which leads to an error.

**Comment by keshrath** [comment]
@Kaliuta Thanks for the feedback, I will analyze it further.

**Comment by AndaChain** [comment]
> He also repeated this mistake. Here are the steps:
> 
> 1. Change the brand color.
> 2. Save.
> 3. Change the brand color again (second time).
> 4. Save.
> 5. Result: Error.
> 
> The error occurs if the website module is installed. Everything works fine without the website module installed.
> 
> I understood that it is related to the method:
> 
> def _get_custom_attachment(self, custom_url, op='=')
> 
> which is located in the path: /addons/website/models/assets.py
> 
> If the override of this method is commented out, there will be no error.
> 
> This requires additional research, but I think the problem is that the attachment is filtered by website_id, and style attachments generated by this module may not have this field, which leads to an error.

Hi, I would like to know, what should I do to fix it? I am not sure what you do. Maybe, you show me your code, to clarify your explanation.

**Comment by keshrath** [comment]
https://github.com/muk-it/odoo-modules/commit/706175b9477aa32c90c3362c97d9155447486174

**Comment by muramez** [comment]
can someone explain me, how i can fix this error? i get always 500 error and dont know how to come back to my odoo instance
